version: "3.8"

services:
  data_preprocessing:
    build:
      context: .
      dockerfile: Dockerfile.data_preprocessing
    volumes:
      - ./shared:/app/shared
    ports:
      - "9001:9001"  
    env_file:
      - .env
    networks:
      - platform_network

  document_analysis:
    build:
      context: .
      dockerfile: Dockerfile.document_analysis
    volumes:
      - ./shared:/app/shared
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - platform_network

  edu_ai_agents:
    build:
      context: .
      dockerfile: Dockerfile.edu_ai_agents
    volumes:
      - ./shared:/app/shared
    ports:
      - "9002:9002"
    env_file:
      - .env
    networks:
      - platform_network

  qa_generation:
    build:
      context: .
      dockerfile: Dockerfile.qa_generation
    volumes:
      - ./shared:/app/shared
    ports:
      - "9004:9004"
    env_file:
      - .env
    networks:
      - platform_network

  face_analysis:
    build:
      context: .
      dockerfile: Dockerfile.face_analysis
    volumes:
      - ./shared:/app/shared
    ports:
      - "9005:9005"
    env_file:
      - .env
    networks:
      - platform_network

networks:
  platform_network:
    external: true