version: '3.8'

services:
  kong-database-edtech-domain:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5431:5431"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migrations-edtech-domain:
    image: kong
    command: kong migrations bootstrap
    depends_on:
      kong-database-edtech-domain:
        condition: service_healthy
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database-edtech-domain
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass

  kong-edtech-domain:
    image: kong
    depends_on:
      kong-migrations-edtech-domain:
        condition: service_completed_successfully
    environment:
      KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE: 50m
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database-edtech-domain
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8090  # Updated to port 8090
      KONG_LOG_LEVEL: debug
    ports:
      - "8090:8090"  # Proxy port
      - "8001:8001"  # Admin API port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml  # Load your kong.yml
