version: "3.8"

services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      - sqlserver-dremio-superset
    ports:
      - "19120:19120"

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      - sqlserver-dremio-superset
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - sqlserver-dremio-superset
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Yourpassword2024"
      ACCEPT_EULA: "Y"
    networks:
      - sqlserver-dremio-superset
    ports:
      - "1433:1433"

  # Superset
  superset:
    image: alexmerced/dremio-superset
    container_name: superset
    networks:
      - sqlserver-dremio-superset
    ports:
      - "8080:8088"

networks:
  sqlserver-dremio-superset: