services:  
  ollama:
      image: ollama/ollama:0.5.1
      container_name: ollama-platform
      ports:
        - "11434:11434"
      volumes:
        - ~/.cache/huggingface:/root/.cache/huggingface
        - ollama:/root/.ollama
      networks:
        - platform_network
        - app_network
      deploy:
        resources:
          reservations:
            devices:
              - driver: "nvidia"
                count: all
                capabilities: [gpu]
networks:
  platform_network:
    external: true
  app_network:
    external: true
volumes:
  ollama:
    driver: local
