version: "3.8"
services:
  ollama:
    image: ollama/ollama:0.5.1
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - platform_network
      - app_network
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped

networks:
  platform_network:
    external: true
  app_network:
    external: true